// B4B validator — Dropzyy settlement ledger
const fs = require("fs");
const path = require("path");
const root = path.join(__dirname, "..");
let fail = 0;
function check(name, cond) {
  console.log((cond ? "PASS" : "FAIL") + " — " + name);
  if (!cond) fail++;
}
const mig = fs.readFileSync(path.join(root, "supabase/migrations/20260910_create_settlement_ledger.sql"), "utf8");
console.log("== FILES ==");
check("migration exists", fs.existsSync(path.join(root, "supabase/migrations/20260910_create_settlement_ledger.sql")));
console.log("\n== VENDOR_SETTLEMENTS ==");
check("table", /CREATE TABLE IF NOT EXISTS public\.vendor_settlements/i.test(mig));
check("id pk", /id uuid PRIMARY KEY DEFAULT gen_random_uuid/i.test(mig));
check("order_id fk", /order_id uuid NOT NULL REFERENCES public\.orders/i.test(mig));
check("vendor_id fk", /vendor_id uuid NOT NULL REFERENCES public\.vendors/i.test(mig));
check("amount not null", /amount numeric NOT NULL/i.test(mig));
check("status default pending", /status text NOT NULL DEFAULT 'pending'/i.test(mig));
check("created_at", /created_at timestamptz/i.test(mig));
check("updated_at", /updated_at timestamptz/i.test(mig));
console.log("\n== DELIVERY_SETTLEMENTS ==");
check("table", /CREATE TABLE IF NOT EXISTS public\.delivery_settlements/i.test(mig));
check("id pk", /id uuid PRIMARY KEY DEFAULT gen_random_uuid/i.test(mig));
check("order_id fk", /order_id uuid NOT NULL REFERENCES public\.orders/i.test(mig));
check("rider_id fk", /rider_id uuid REFERENCES public\.profiles/i.test(mig));
check("delivery_fee", /delivery_fee numeric NOT NULL/i.test(mig));
check("rider_amount", /rider_amount numeric NOT NULL/i.test(mig));
check("platform_amount", /platform_amount numeric NOT NULL/i.test(mig));
check("status default pending", /status text NOT NULL DEFAULT 'pending'/i.test(mig));
console.log("\n== REFUNDS ==");
check("table", /CREATE TABLE IF NOT EXISTS public\.refunds/i.test(mig));
check("id pk", /id uuid PRIMARY KEY DEFAULT gen_random_uuid/i.test(mig));
check("payment_id fk", /payment_id uuid NOT NULL REFERENCES public\.payments/i.test(mig));
console.log("\n== UNIQUE CONSTRAINTS ==");
check("vendor_settlements order+vendor unique", /vendor_settlements_order_vendor_key/i.test(mig));
check("delivery_settlements order unique", /delivery_settlements_order_key/i.test(mig));
check("refunds gateway_refund_id unique", /refunds_gateway_refund_id_key/i.test(mig));
console.log("\n== CHECK CONSTRAINTS ==");
check("vendor amount>=0", /vendor_settlements_amount_check/i.test(mig));
check("vendor status chk", /vendor_settlements_status_check/i.test(mig));
check("delivery fee>=0", /delivery_settlements_fee_check/i.test(mig));
check("rider amount>=0", /delivery_settlements_rider_check/i.test(mig));
check("platform amount>=0", /delivery_settlements_platform_check/i.test(mig));
check("delivery status chk", /delivery_settlements_status_check/i.test(mig));
check("rider+platform=fee", /delivery_settlements_split_check/i.test(mig));
check("refund amount>0", /refunds_amount_check/i.test(mig));
check("refund status chk", /refunds_status_check/i.test(mig));
console.log("\n== INDEXES ==");
check("idx vendor order_id", /idx_vendor_settlements_order_id/i.test(mig));
check("idx vendor vendor_id", /idx_vendor_settlements_vendor_id/i.test(mig));
check("idx vendor status", /idx_vendor_settlements_status/i.test(mig));
check("idx delivery order_id", /idx_delivery_settlements_order_id/i.test(mig));
check("idx delivery rider_id", /idx_delivery_settlements_rider_id/i.test(mig));
check("idx delivery status", /idx_delivery_settlements_status/i.test(mig));
check("idx refunds payment_id", /idx_refunds_payment_id/i.test(mig));
check("idx refunds order_id", /idx_refunds_order_id/i.test(mig));
check("idx refunds status", /idx_refunds_status/i.test(mig));
console.log("\n== UPDATED_AT TRIGGERS ==");
check("set_settlements_updated_at", /set_settlements_updated_at/i.test(mig));
check("trg_vendor/delivery/refunds_updated_at", /trg_vendor_settlements_updated_at|trg_delivery_settlements_updated_at|trg_refunds_updated_at/i.test(mig));
check("updated_at triggers exist", /trg_settlements_updated_at|trg_vendor_settlements_updated_at/i.test(mig));
console.log("\n== RLS ==");
check("vendor_settlements RLS", /ALTER TABLE public\.vendor_settlements ENABLE ROW LEVEL SECURITY/i.test(mig));
check("delivery_settlements RLS", /ALTER TABLE public\.delivery_settlements ENABLE ROW LEVEL SECURITY/i.test(mig));
check("refunds RLS", /ALTER TABLE public\.refunds ENABLE ROW LEVEL SECURITY/i.test(mig));
check("vendors_read_own_settlements", /vendors_read_own_settlements/i.test(mig));
check("riders_read_own_deliveries", /riders_read_own_deliveries/i.test(mig));
check("customers_read_own_refunds", /customers_read_own_refunds/i.test(mig));
check("no_client_insert_vendor", /no_client_insert_vendor_settlements/i.test(mig));
check("no_client_update_vendor", /no_client_update_vendor_settlements/i.test(mig));
check("no_client_delete_vendor", /no_client_delete_vendor_settlements/i.test(mig));
check("no_client_insert_delivery", /no_client_insert_delivery_settlements/i.test(mig));
check("no_client_update_delivery", /no_client_update_delivery_settlements/i.test(mig));
check("no_client_delete_delivery", /no_client_delete_delivery_settlements/i.test(mig));
check("no_client_insert_refunds", /no_client_insert_refunds/i.test(mig));
check("no_client_update_refunds", /no_client_update_refunds/i.test(mig));
check("no_client_delete_refunds", /no_client_delete_refunds/i.test(mig));
check("REVOKE vendor", /REVOKE ALL ON public\.vendor_settlements FROM anon, authenticated/i.test(mig));
check("REVOKE delivery", /REVOKE ALL ON public\.delivery_settlements FROM anon, authenticated/i.test(mig));
check("REVOKE refunds", /REVOKE ALL ON public\.refunds FROM anon, authenticated/i.test(mig));
check("GRANT SELECT vendor", /GRANT SELECT ON public\.vendor_settlements TO authenticated/i.test(mig));
check("GRANT SELECT delivery", /GRANT SELECT ON public\.delivery_settlements TO authenticated/i.test(mig));
check("GRANT SELECT refunds", /GRANT SELECT ON public\.refunds TO authenticated/i.test(mig));
console.log("\n== GENERATE_SETTLEMENT RPC ==");
check("fn exists", /CREATE OR REPLACE FUNCTION public\.generate_settlement/i.test(mig));
check("SECURITY DEFINER", /generate_settlement[\s\S]*?SECURITY DEFINER/i.test(mig));
check("locks order FOR UPDATE", /generate_settlement[\s\S]*?FOR UPDATE/i.test(mig));
check("verify payment success", /generate_settlement[\s\S]*?status = 'success'/i.test(mig));
check("verify delivered", /generate_settlement[\s\S]*?status != 'Delivered'/i.test(mig));
check("idempotency check", /generate_settlement[\s\S]*?already_exists/i.test(mig));
check("vendor settlement from order_items", /generate_settlement[\s\S]*?SUM\(oi\.price \* oi\.qty\)/i.test(mig));
check("delivery uses orders.fee", /generate_settlement[\s\S]*?v_order\.fee/i.test(mig));
check("80/20 split", /generate_settlement[\s\S]*?fee \* 0\.8/i.test(mig));
check("status pending", /generate_settlement[\s\S]*?\'pending\'/i.test(mig));
console.log("\n== NO PAYSTACK TRANSFER ==");
check("no transfer API call", !/transfer\.paystack\.co|transaction\.transfer/i.test(mig));
check("no split payment", !/split_payment|Paystack\.Split/i.test(mig));
console.log("\n== B1/B4A PRESERVED ==");
const b1 = fs.readFileSync(path.join(root, "supabase/migrations/20260907_lock_order_payment_columns.sql"), "utf8");
check("B1 trigger", /CREATE OR REPLACE FUNCTION public\.prevent_order_unauthorized_changes/i.test(b1));
const b4a = fs.readFileSync(path.join(root, "supabase/migrations/20260909_create_payments_ledger.sql"), "utf8");
check("B4A payments table", /CREATE TABLE IF NOT EXISTS public\.payments/i.test(b4a));
check("B4A success RPC", /public\.handle_paystack_payment_success/i.test(b4a));
console.log("\n== SECRET LEAK SCAN ==");
const assetsDir = path.join(root, "assets");
let leak = false;
(function walk(dir) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (e.name === "node_modules" || e.name === ".git") continue;
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p);
    else if (/\.(js|html|css|json)$/i.test(e.name)) {
      const c = fs.readFileSync(p, "utf8");
      if (/sk_live_[A-Za-z0-9]/.test(c) || /sk_test_[A-Za-z0-9]/.test(c) || /sb_secret_[A-Za-z0-9]/.test(c)) {
        leak = true; console.log("  LEAK: " + path.relative(root, p));
      }
    }
  }
})(assetsDir);
check("no secret in assets", !leak);
console.log("\n==============================");
console.log(fail ? "B4B VALIDATION FAILED" : "B4B ALL CHECKS PASSED");
console.log("==============================");
process.exit(fail ? 1 : 0);
check("order_id fk", /order_id uuid NOT NULL REFERENCES public\.orders/i.test(mig));
check("amount", /amount numeric NOT NULL/i.test(mig));
check("status default pending", /status text NOT NULL DEFAULT 'pending'/i.test(mig));
check("reason", /reason text/i.test(mig));
check("gateway_refund_id", /gateway_refund_id text/i.test(mig));
